CREATE TABLE BUNDLE_ACTIONS -- BundleActionBean
    (bundle_action_id VARCHAR(255) NOT NULL, bundle_id VARCHAR(255), coord_id VARCHAR(255), coord_name VARCHAR(255), critical INTEGER, last_modified_time TIMESTAMP, pending INTEGER, status VARCHAR(255), bean_type VARCHAR(31), PRIMARY KEY (bundle_action_id));
CREATE TABLE BUNDLE_JOBS -- JsonBundleJob
    (id VARCHAR(255) NOT NULL, app_name VARCHAR(255), app_path VARCHAR(255), conf CLOB, external_id VARCHAR(255), group_name VARCHAR(255), time_out INTEGER, user_name VARCHAR(255), bean_type VARCHAR(31), created_time TIMESTAMP, end_time TIMESTAMP, job_xml CLOB, kickoff_time TIMESTAMP, last_modified_time TIMESTAMP, orig_job_xml CLOB, pause_time TIMESTAMP, pending INTEGER, start_time TIMESTAMP, status VARCHAR(255), suspended_time TIMESTAMP, time_unit VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE COORD_ACTIONS -- JsonCoordinatorAction
    (id VARCHAR(255) NOT NULL, action_number INTEGER, action_xml CLOB, console_url VARCHAR(255), created_conf CLOB, error_code VARCHAR(255), error_message VARCHAR(255), external_status VARCHAR(255), missing_dependencies CLOB, push_missing_dependencies CLOB, run_conf CLOB, time_out INTEGER, tracker_uri VARCHAR(255), job_type VARCHAR(255), bean_type VARCHAR(31), created_time TIMESTAMP, external_id VARCHAR(255), job_id VARCHAR(255), last_modified_time TIMESTAMP, nominal_time TIMESTAMP, pending INTEGER, rerun_time TIMESTAMP, sla_xml CLOB, status VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE COORD_JOBS -- JsonCoordinatorJob
    (id VARCHAR(255) NOT NULL, app_name VARCHAR(255), app_path VARCHAR(255), bundle_id VARCHAR(255), concurrency INTEGER, conf CLOB, external_id VARCHAR(255), frequency VARCHAR(255), group_name VARCHAR(255), last_action_number INTEGER, mat_throttling INTEGER, time_out INTEGER, time_zone VARCHAR(255), user_name VARCHAR(255), bean_type VARCHAR(31), app_namespace VARCHAR(255), created_time TIMESTAMP, done_materialization INTEGER, end_time TIMESTAMP, execution VARCHAR(255), job_xml CLOB, last_action TIMESTAMP, last_modified_time TIMESTAMP, next_matd_time TIMESTAMP, orig_job_xml CLOB, pause_time TIMESTAMP, pending INTEGER, sla_xml CLOB, start_time TIMESTAMP, status VARCHAR(255), suspended_time TIMESTAMP, time_unit VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE SLA_EVENTS -- JsonSLAEvent
    (event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY, alert_contact VARCHAR(255), alert_frequency VARCHAR(255), alert_percentage VARCHAR(255), app_name VARCHAR(255), dev_contact VARCHAR(255), group_name VARCHAR(255), job_data CLOB, notification_msg CLOB, parent_client_id VARCHAR(255), parent_sla_id VARCHAR(255), qa_contact VARCHAR(255), se_contact VARCHAR(255), sla_id VARCHAR(255), upstream_apps CLOB, user_name VARCHAR(255), bean_type VARCHAR(31), app_type VARCHAR(255), event_type VARCHAR(255), expected_end TIMESTAMP, expected_start TIMESTAMP, job_status VARCHAR(255), status_timestamp TIMESTAMP, PRIMARY KEY (event_id));
CREATE TABLE SLA_REGISTRATION -- SLARegistrationBean
    (job_id VARCHAR(255) NOT NULL, app_name VARCHAR(255), app_type VARCHAR(255), expected_duration BIGINT, expected_end TIMESTAMP, expected_start TIMESTAMP, job_data VARCHAR(255), nominal_time TIMESTAMP, notification_msg VARCHAR(255), parent_id VARCHAR(255), sla_config VARCHAR(255), upstream_apps VARCHAR(255), user_name VARCHAR(255), PRIMARY KEY (job_id));
CREATE TABLE SLA_SUMMARY -- SLASummaryBean
    (job_id VARCHAR(255) NOT NULL, actual_duration BIGINT, actual_end TIMESTAMP, actual_start TIMESTAMP, app_name VARCHAR(255), app_type VARCHAR(255), event_processed SMALLINT, event_status VARCHAR(255), expected_duration BIGINT, expected_end TIMESTAMP, expected_start TIMESTAMP, job_status VARCHAR(255), last_modified TIMESTAMP, nominal_time TIMESTAMP, parent_id VARCHAR(255), sla_status VARCHAR(255), user_name VARCHAR(255), PRIMARY KEY (job_id));
CREATE TABLE VALIDATE_CONN -- ValidateConnectionBean
    (id BIGINT NOT NULL, -- datastore id
    dummy INTEGER, PRIMARY KEY (id));
CREATE TABLE WF_ACTIONS -- JsonWorkflowAction
    (id VARCHAR(255) NOT NULL, conf CLOB, console_url VARCHAR(255), cred VARCHAR(255), data CLOB, error_code VARCHAR(255), error_message VARCHAR(500), external_child_ids CLOB, external_id VARCHAR(255), external_status VARCHAR(255), name VARCHAR(255), retries INTEGER, stats CLOB, tracker_uri VARCHAR(255), transition VARCHAR(255), type VARCHAR(255), user_retry_count INTEGER, user_retry_interval INTEGER, user_retry_max INTEGER, bean_type VARCHAR(31), end_time TIMESTAMP, execution_path VARCHAR(1024), last_check_time TIMESTAMP, log_token VARCHAR(255), pending INTEGER, pending_age TIMESTAMP, signal_value VARCHAR(255), sla_xml CLOB, start_time TIMESTAMP, status VARCHAR(255), wf_id VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE WF_JOBS -- JsonWorkflowJob
    (id VARCHAR(255) NOT NULL, app_name VARCHAR(255), app_path VARCHAR(255), conf CLOB, group_name VARCHAR(255), parent_id VARCHAR(255), run INTEGER, user_name VARCHAR(255), bean_type VARCHAR(31), created_time TIMESTAMP, end_time TIMESTAMP, external_id VARCHAR(255), last_modified_time TIMESTAMP, log_token VARCHAR(255), proto_action_conf CLOB, sla_xml CLOB, start_time TIMESTAMP, status VARCHAR(255), wf_instance BLOB, PRIMARY KEY (id));
CREATE INDEX I_BNDLTNS_DTYPE ON BUNDLE_ACTIONS (bean_type);
CREATE INDEX I_BNDLJBS_CREATED_TIME ON BUNDLE_JOBS (created_time);
CREATE INDEX I_BNDLJBS_DTYPE ON BUNDLE_JOBS (bean_type);
CREATE INDEX I_BNDLJBS_LAST_MODIFIED_TIME ON BUNDLE_JOBS (last_modified_time);
CREATE INDEX I_BNDLJBS_STATUS ON BUNDLE_JOBS (status);
CREATE INDEX I_BNDLJBS_SUSPENDED_TIME ON BUNDLE_JOBS (suspended_time);
CREATE INDEX I_CRD_TNS_CREATED_TIME ON COORD_ACTIONS (created_time);
CREATE INDEX I_CRD_TNS_DTYPE ON COORD_ACTIONS (bean_type);
CREATE INDEX I_CRD_TNS_EXTERNAL_ID ON COORD_ACTIONS (external_id);
CREATE INDEX I_CRD_TNS_JOB_ID ON COORD_ACTIONS (job_id);
CREATE INDEX I_CRD_TNS_LAST_MODIFIED_TIME ON COORD_ACTIONS (last_modified_time);
CREATE INDEX I_CRD_TNS_NOMINAL_TIME ON COORD_ACTIONS (nominal_time);
CREATE INDEX I_CRD_TNS_RERUN_TIME ON COORD_ACTIONS (rerun_time);
CREATE INDEX I_CRD_TNS_STATUS ON COORD_ACTIONS (status);
CREATE INDEX I_CRD_JBS_CREATED_TIME ON COORD_JOBS (created_time);
CREATE INDEX I_CRD_JBS_DTYPE ON COORD_JOBS (bean_type);
CREATE INDEX I_CRD_JBS_LAST_MODIFIED_TIME ON COORD_JOBS (last_modified_time);
CREATE INDEX I_CRD_JBS_NEXT_MATD_TIME ON COORD_JOBS (next_matd_time);
CREATE INDEX I_CRD_JBS_STATUS ON COORD_JOBS (status);
CREATE INDEX I_CRD_JBS_SUSPENDED_TIME ON COORD_JOBS (suspended_time);
CREATE INDEX I_SL_VNTS_DTYPE ON SLA_EVENTS (bean_type);
CREATE INDEX I_SL_RRTN_NOMINAL_TIME ON SLA_REGISTRATION (nominal_time);
CREATE INDEX I_SL_SMRY_APP_NAME ON SLA_SUMMARY (app_name);
CREATE INDEX I_SL_SMRY_EVENT_PROCESSED ON SLA_SUMMARY (event_processed);
CREATE INDEX I_SL_SMRY_LAST_MODIFIED ON SLA_SUMMARY (last_modified);
CREATE INDEX I_SL_SMRY_NOMINAL_TIME ON SLA_SUMMARY (nominal_time);
CREATE INDEX I_SL_SMRY_PARENT_ID ON SLA_SUMMARY (parent_id);
CREATE INDEX I_WF_CTNS_DTYPE ON WF_ACTIONS (bean_type);
CREATE INDEX I_WF_CTNS_PENDING_AGE ON WF_ACTIONS (pending_age);
CREATE INDEX I_WF_CTNS_STATUS ON WF_ACTIONS (status);
CREATE INDEX I_WF_CTNS_WF_ID ON WF_ACTIONS (wf_id);
CREATE INDEX I_WF_JOBS_DTYPE ON WF_JOBS (bean_type);
CREATE INDEX I_WF_JOBS_END_TIME ON WF_JOBS (end_time);
CREATE INDEX I_WF_JOBS_EXTERNAL_ID ON WF_JOBS (external_id);
CREATE INDEX I_WF_JOBS_LAST_MODIFIED_TIME ON WF_JOBS (last_modified_time);
CREATE INDEX I_WF_JOBS_STATUS ON WF_JOBS (status);

create table OOZIE_SYS (name varchar(100), data varchar(100))
insert into OOZIE_SYS (name, data) values ('db.version', '2')
insert into OOZIE_SYS (name, data) values ('oozie.version', '4.0.1')
